
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    username: root
#  security:
#    user:
#      name: admin
#      password: admin
